---
- name: Install Apache and deploy index.html
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure Apache (httpd) is installed
      dnf:  # Using dnf as package manager for Oracle Linux 9
        name: httpd
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: httpd  # Apache service is named 'httpd' on Oracle Linux 9
        state: started
        enabled: yes

    - name: Deploy index.html to the document root
      copy:
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Welcome</title>
          </head>
          <body>
              <h1>Welcome to the Apache Server!</h1>
              <p>This is a test page.</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: apache   # Ensure the owner is 'apache' on Oracle Linux 9
        group: apache   # Ensure the group is 'apache' on Oracle Linux 9
        mode: '0644'
